controller_list:
  - name: fake_right_arm_controller
    type: last point
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2
  - name: fake_left_arm_controller
    type: last point
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
  - name: fake_left_eef_controller
    type: last point
    joints:
      - left_gripper_base
      - left_endpoint
      - l_gripper_l_finger_joint
      - l_gripper_r_finger_joint
  - name: fake_right_eef_controller
    type: last point
    joints:
      - right_gripper_base
      - right_endpoint
      - r_gripper_l_finger_joint
      - r_gripper_r_finger_joint
